name: Terraform GCP Infra

on:
  push:
    branches:
      - main

# ✅ ADD THIS BLOCK (CRITICAL FIX)
permissions:
  id-token: write   # REQUIRED for WIF
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: "projects/345641983266/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform-sa@project-24a83cf8-3efa-4d50-afd.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd gcp-etl-template/terraform
          terraform init

      - name: Terraform Plan
        run: |
          cd gcp-etl-template/terraform
          terraform plan

      - name: Terraform Apply
        run: |
          cd gcp-etl-template/terraform
          terraform apply -auto-approve
